Adding user controlled feature and can be executed with command line
Tejas1510/Hacking-Scripts pull request #192
Opened 2021-01-23 21:14 UTC by 7saikat7

Fixes #

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### Description:

system will ask phone number , content of message , time and seconds to confirm when the msg will be sent , then it will automatically login in whatsapp and will send the message. 

### Change logs:

-->

### Fixed:
User can use it via command line , by activating hack venv , which is ignored here 

### Snapshot:

2021-01-24 05:14 UTC, Tejas1510 commented
@7saikat7 please add a Proper Readme File with the format suggested

2021-01-24 16:58 UTC, atarax665 requested changes

2021-01-24 16:58 UTC, atarax665 commented on Python/Bulk_message_whatsapp/whatsapp.py
> +import pywhatkit
Format your code according to PEP8 guidelines.

2021-01-25 19:40 UTC, Tejas1510 commented
Awesome work @7saikat7

2021-01-25 19:40 UTC, merged