Covid19 tracker application
Tejas1510/Hacking-Scripts pull request #448
Opened 2021-06-13 13:08 UTC by LasyaGanesuni

## Explanation

  
Fixes #443

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

2021-06-13 14:02 UTC, amanjha8100 requested changes
In documentation it will be ```pip install tk```, then you forgot to mention covid python package as a dependency. Look into this.

2021-06-13 14:20 UTC, amanjha8100 commented
and specify why you using numpy for?

2021-06-14 05:20 UTC, LasyaGanesuni commented
@amanjha8100, I have made the mentioned changes. Please check it once.

2021-06-14 13:08 UTC, amanjha8100 approved these changes

2021-06-14 13:08 UTC, merged