2048 Game
Tejas1510/Hacking-Scripts pull request #911
Opened 2021-07-04 17:36 UTC by neelshah2409

## Explanation
  2048 a game developed in python programming Language using random module and tkinter module.
It is a single player sliding tile puzzle game
The user can keep playing till he gets a 2048 tile or all the grids are full and no grids can be merged

Fixes #908 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

## Output
![output_1(2048)](https://user-images.githubusercontent.com/71593494/124394239-461c1380-dd1c-11eb-92f0-48e124f0dfd9.png)
![output_2(2048)](https://user-images.githubusercontent.com/71593494/124394240-487e6d80-dd1c-11eb-815e-17463db80aba.png)

2021-07-05 05:19 UTC, GowthamGoush requested changes
Please consider removing the changes to the irrelevant readme.

2021-07-05 06:02 UTC, neelshah2409 commented
@GowthamGoush Sir I had updated my readme ,please see it.

2021-07-05 07:33 UTC, GowthamGoush reviewed
I've mentioned the required changes below.

2021-07-05 07:33 UTC, GowthamGoush commented on Python/Job Finder Helper/README.md
> +# Job Finder Helper
Consider removing the changes in this readme.

2021-07-05 07:33 UTC, GowthamGoush commented
Also, you may feel free to call me by my name.

2021-07-05 16:36 UTC, neelshah2409 commented
@GowthamGoush I had done the changes please review it.

2021-07-06 05:28 UTC, neelshah2409 commented
@GowthamGoush Please see this PR.

2021-07-06 06:04 UTC, GowthamGoush commented
The changes are still reflected @neelshah2409. Try to copy/paste the exact data into that readme.

2021-07-06 08:55 UTC, neelshah2409 commented
> The changes are still reflected @neelshah2409. Try to copy/paste the exact data into that readme.

@GowthamGoush sir I am not getting still if you tell than I may make a new  PR and you can close if you tell . Please help.

2021-07-07 06:37 UTC, GowthamGoush commented
Hey, @neelshah2409, no worries. All you have to do is remove any changes you've made to the `Python/Job Finder Helper/README.md`. You may reset the head or copy/paste the original copy, or create a new branch and push only those changes concerned with your script.

2021-07-09 05:30 UTC, GowthamGoush commented
@neelshah2409, even deleting the readme will be reflected as change. Consider creating a new branch and pushing all the necessary changes into that.

2021-07-10 08:32 UTC, neelshah2409 commented
@GowthamGoush Sir please see if it is done or sir please close this PR I will make another for this please reply sir because today is last day.

2021-07-10 08:43 UTC, closed without merging