Image Cartoonifier added in Image Editor (Python)
Tejas1510/Hacking-Scripts pull request #973
Opened 2021-07-09 06:49 UTC by neelshah2409

## Explanation
Here we convert the simple image into cartoonified using cv library , here we first get the image then we change the grey scales and image shades so then the output carttonified image will be shown.
  
Fixes #964 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

# Screenshots:

- Real image

![image](https://user-images.githubusercontent.com/71593494/125035712-c5f50580-e0af-11eb-80f9-bba1633e24fc.jpg)

- Cartoonified Image

![output(cartoon)](https://user-images.githubusercontent.com/71593494/125035780-dc02c600-e0af-11eb-9b7c-90b31405f333.png)

2021-07-09 06:50 UTC, neelshah2409 commented
@RaveenaBhasin @GowthamGoush @mehabhalodiya Please review this PR.

2021-07-09 13:05 UTC, GowthamGoush approved these changes

2021-07-09 13:09 UTC, GowthamGoush requested changes
One last step, update the readme accordingly.

2021-07-09 13:26 UTC, neelshah2409 commented
@GowthamGoush Please see the changes I had updated the readme.

2021-07-10 07:47 UTC, GowthamGoush approved these changes

2021-07-10 07:47 UTC, merged